forecasts:
    # standalone forecasts = "pure" toy models forecasts without any extra component (DFI, IAU, Fullpos...)
    - standalone_alaro_antwrp1300
    - standalone_alaro1sfx_chmh2325
    - standalone_arome_corsica2500
    - standalone_arpege_globaltst149c24
    - standalone_arpege_nosfx_globaltst149c24
    - standalone_ifs_global21
    # canonical forecasts = close to operations, including extra components
    - canonical_arpege_global798c22
    - canonical_arpege_apl_global798c22

assim:
    # arpege
    - arpege_BA4DVar_OOPS  # BA = Bator+Analysis (all-in-one)
    - arpege_BSHM4DVar_OOPS  # BSM = Bator+Screening+H(TL/AD)+Minim
    - arpege_BSM4DVar_CNT0  # BSM = Bator+Screening+Minim
    - arpege_BSHM3DVar_OOPS  # BSM = Bator+Screening+H(TL/AD)+Minim
    - arpege_BSM3DVar_CNT0  # BSM = Bator+Screening+Minim
    - arpege_BC  # BC = Bator(surf)+Canari
    # arome
    - arome_BSM3DVar_CNT0  # BSM = Bator+Screening+Minim
    - arome_BA3DVar_OOPS  # BA = Bator+Analysis (all-in-one)
    - arome_BSM3DVar_OOPS  # BSM = Bator+Screening+Minim
    # one obstype at a time -- Bator+Screening only
    - arpege_BS3D__obstype
    - arpege_BS4D__obstype
    - arome_BS3D_CNT0__obstype
    - arome_BS3D_OOPS__obstype

oops:
    - ObsOp4D_arpege  # Tests of 4D Observation operators (NL, TL, AD), one obstype at a time
    - ObsOp3D_arpege  # Tests of 3D Observation operators (NL, TL, AD), one obstype at a time
    - Bmat_arpege  # Construction and reading of a B-matrix using an ensemble, EnVar unit tests
    - Bmat_arome  # Construction and reading of a B-matrix using an ensemble, EnVar unit tests
    - ModelTLAD_arpege # TL model, adjoint test

misc:
    - Physiography_arome   # PGD + clim 923(N923=1) on a range of LAM geometries

fullpos:
    - LBC  # Fullpos creation of LBC files

surfex:
    - PP_arome   # PP_arome  = PGD+Prep on a LAM geometry
    - PP_arpege  # PP_arpege = PGD+Prep on Gauss grids

# mixs: jobs containing several tasks of various families
#mixs:
#    - PF  # Prep-Forecast (using older PGD)
#    - PPF  # PGD-Prep-Forecast (using new PGD)

